### ISSUE TITLE
Revalidating A Property

### ISSUE THREAD

**Issue by MatthewPringle** [adopted-ember-addons/ember-cp-validations#508] opened 2017-05-15 10:16 UTC
The scenario...

I have 2 fields

The first field is a select with 3 options, null / No / Yes

The second field is a text field.

I am showing the text field when the select field equals "Yes"

In the validate file I am adding a computed property to 'disabled' so the question doesn't validate when it is hidden. Which works.

However, the original validation persists when being hidden. The field does not get validated ( and why would it ).

So my question, is there a way to revalidate ( or reset ) a specific field's validation?

**Comment by offirgolan** [comment] 2017-05-15 17:24
@MatthewPringle Im not sure I follow you here. Can you add some more details and maybe some code snippets?

**Comment by MatthewPringle** [comment] 2017-05-15 18:01
@offirgolan thanks for the reply. I think I may have solved it, just, but it needs testing etc... But if you have any better ideas...

A very basic example:

The form consists of 2 questions. One is a <select> and the other is a hidden <input type="text">

<label>Do you want free stuff?</label>
<select>
<option value="">Please Select</option>
<option value="Yes">Yes</option>
<option value="No">No</option>
</select>

The <select> is validated on presence, "Yes" or "No" are both acceptable answers.

questionSelectYesNo: validator( 'presence' , true )

So far so good

If the user selects "Yes" then an additional question is shown. This is done by the question component watching the model for when questionSelectYesNo === "Yes"

<label>What would you like?</label>
<input type="text">

I first thought ( and was advised by the helpful people on Slack ) to look at dependentKeys as a way of only validating the second question if the first question === "Yes".

Unfortunately ( from what I can gather ) dependentKeys is true if the first question is set to either "Yes" or "No" as it doesn't accept a 2nd parameter.

After a lot of playing about I came up with the following (code a bit rough )

`questionText: {
        disabled: Ember.computed( 'model.questionSelectYesNo' , function() {
            return this.get( 'model.questionSelectYesNo' ) === 'Yes' ? false : true;
        }).volatile(),
        validators: [
            validator( 'Conditional' , { conditionalField: 'questionSelectYesNo' , conditionalValue: 'Yes' } )
        ]
}`

I first watch and disable / enable the question depending on if "Yes" is selected.

I then pass the validation over to a custom validator which checks if the first question !== "Yes", and therefore passes True, so the question is treated as valid. Essentially stopping the hidden question from validating, causing the form not to submit etc...

`const Conditional = BaseValidator.extend({

    validate( value , options , model , attribute ) {
        
        var conditionalField = options.get( 'conditionalField' );
        var conditionalValue = options.get( 'conditionalValue' );
        
        if ( conditionalField && conditionalValue ) {
        
            var conditionalFieldValue = model.get( conditionalField );
        
            if ( conditionalFieldValue !== conditionalValue ) {
                return true;
            }
        
        }
 
        /* Validation Result */
        var result = false;
         
        if ( value ) {
            result = true;
        }    
        
        /* Return */
        return ( result === true ) ? true : 'Please enter a thing!!!';
    }
});
export default Conditional;`

This seems to work, the second question, upon being hidden, revalidates to true, the .volatile() helped with that, as otherwise it wasn't always updating.

**Comment by offirgolan** [comment] 2017-05-20 23:35
@MatthewPringle I think the issue is because you didnt add the necessary dependent key to your `conditional` validator. See below:

```js
const Conditional = BaseValidator.extend({
    validate( value , options , model , attribute ) {
        // ...
    }
});

// Add the conditionalField as a dependent key
Conditional.reopenClass({
  getDependentsFor(attribute, options) {
    return [`model.${options.conditionalField }`];
  }
});

export default Conditional;
```

**Comment by offirgolan** [comment] 2017-05-20 23:38
Also, why is your `disabled` option `volatile`? I dont think thats necessary.

**Comment by fsmanuel** [comment] 2022-09-11 11:04
@MatthewPringle I'm closing the issue because it's quite old. Feel free to reopen if you need more help.

**Closed by fsmanuel** 2022-09-11 11:04 UTC

**Comment by mattsputnikdigital** [comment] 2022-09-12 09:53
@fsmanuel Thanks, I solved it with the advice given above. The form / validations have been used by millions of customers and has been a joy to use without any issues.
